'''

389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''

# Version 1:
'''
1. Create dictionary where keys are characters and values are counts
2. Iterate over t, and find count -1, if count == -1, then return the current character.
'''
class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        # Count the existence of each character.
        # Or use collections.Count if allowed
        s_d = {}
        for char_s in s:
            s_d[char_s] = s_d.get(char_s, 0) + 1

        for char_t in t:
            s_d[char_t] = s_d.get(char_t, 0) - 1
            if s_d[char_t] == -1:
                return char_t

# Version 2: Use XOR
class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        ans = 0
        for c in s + t:
            ans ^= ord(c)
        return chr(ans)

aa = Solution()
print(aa.findTheDifference('abcd', 'abcde'))
print(aa.findTheDifference('a', 'aa'))
